[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "SurvivalElements"
versionNumber = "1.0.2"
description = "Adds survival mechanics including the Repair Tool for maintaining and repairing machines."
websiteUrl = "https://github.com/xXDeath420Xx/TTMod-SurvivalElements"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"
CertiFried-TechtonicaFramework = "1.0.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net472/SurvivalElements.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
